package everlongrebalancer

import (
	"encoding/csv"
	"math/big"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
)

// crCase is one row of testdata/collvault_fixtures.csv — ground truth generated by a
// forge script executing the shipped CollRebalancerMath library over a grid of position
// states: half-law, join edge, Hermite, wall boundary, missed-wall recovery
// (deleverage-only conservative continuation), rescue-spread band and insolvent states,
// across two price frames and two posted spreads.
type crCase struct {
	kind                    string
	collateral, debt, price *big.Int
	spread, amountIn        *big.Int
	out, newColl, newDebt   *big.Int
	preAnchor               *big.Int
	safeAfter               bool
}

func loadCRFixtures(t *testing.T) []crCase {
	t.Helper()
	f, err := os.Open("testdata/collvault_fixtures.csv")
	require.NoError(t, err)
	defer func() { _ = f.Close() }()
	rows, err := csv.NewReader(f).ReadAll()
	require.NoError(t, err)
	require.Greater(t, len(rows), 1)

	u := func(s string) *big.Int {
		v, ok := new(big.Int).SetString(s, 10)
		require.True(t, ok, "bad fixture int %q", s)
		return v
	}
	cases := make([]crCase, 0, len(rows)-1)
	for _, r := range rows[1:] {
		cases = append(cases, crCase{
			kind: r[0], collateral: u(r[1]), debt: u(r[2]), price: u(r[3]),
			spread: u(r[4]), amountIn: u(r[5]),
			out: u(r[6]), newColl: u(r[7]), newDebt: u(r[8]),
			preAnchor: u(r[9]), safeAfter: r[10] == "1",
		})
	}
	return cases
}

// TestQuotesMatchShippedLibrary: leverageQuote / deleverageQuote (including the
// missed-wall recovery continuation), the pre-fill anchor and the fill-acceptance
// predicate must all be wei-exact against the shipped library bytecode.
func TestQuotesMatchShippedLibrary(t *testing.T) {
	cp := berachainCurveParams()
	cases := loadCRFixtures(t)
	recoveryQuoted := 0
	for i, c := range cases {
		var out, newColl, newDebt *big.Int
		if c.kind == "L" {
			out, newColl, newDebt = cp.leverageQuote(c.collateral, c.debt, c.price,
				cp.LeverageRatioWad, c.spread, c.amountIn)
		} else {
			out, newColl, newDebt = cp.deleverageQuote(c.collateral, c.debt, c.price,
				cp.LeverageRatioWad, c.spread, c.amountIn)
			if out.Sign() != 0 && cp.stateRegion(c.collateral, c.debt, c.price) == regionRecovery {
				recoveryQuoted++
			}
		}
		require.Zero(t, c.out.Cmp(out), "case %d (%s) out got=%s want=%s", i, c.kind, out, c.out)
		require.Zero(t, c.newColl.Cmp(newColl), "case %d (%s) newColl", i, c.kind)
		require.Zero(t, c.newDebt.Cmp(newDebt), "case %d (%s) newDebt", i, c.kind)

		preAnchor := cp.xAnchorForState(c.collateral, c.debt, c.price)
		require.Zero(t, c.preAnchor.Cmp(preAnchor), "case %d preAnchor got=%s want=%s",
			i, preAnchor, c.preAnchor)
		require.Equal(t, c.safeAfter, cp.isStateSafe(newColl, newDebt, c.price, preAnchor),
			"case %d isStateSafe", i)
	}
	// The grid must actually exercise the recovery continuation, or the port of that
	// branch is untested.
	require.Greater(t, recoveryQuoted, 0, "fixtures must include quoting recovery states")
}

// TestLiveCurveOverlayRejectsDegenerate: the overlay replaces the validated frozen
// constants for every quote, and its read is TOLERATED, so a partial or degenerate tuple
// must be refused rather than adopted. A zero Width divides by zero on the first quote;
// a nil Bezier word panics in the lerp.
func TestLiveCurveOverlayRejectsDegenerate(t *testing.T) {
	good := berachainCurveParams()
	require.True(t, good.usable(), "the shipped constants must pass their own bar")

	zeroWidth := berachainCurveParams()
	zeroWidth.Width = big.NewInt(0)
	require.False(t, zeroWidth.usable(), "a zero Width divides by zero in debtNormWad")

	nilBezier := berachainCurveParams()
	nilBezier.BezierPhi[2] = nil
	require.False(t, nilBezier.usable(), "a nil Bezier control panics in the lerp")

	nilIntegral := berachainCurveParams()
	nilIntegral.BezierIntegral[3] = nil
	require.False(t, nilIntegral.usable())

	wallOrder := berachainCurveParams()
	wallOrder.DWall = new(big.Int).Add(wallOrder.HWall, big.NewInt(1))
	require.False(t, wallOrder.usable(), "DWall past HWall makes the recovery sqrt negative")
}
